create table "public"."authors" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "email" text
);


alter table "public"."authors" enable row level security;

alter table "public"."notes" add column "author_id" bigint;

CREATE UNIQUE INDEX authors_pkey ON public.authors USING btree (id);

alter table "public"."authors" add constraint "authors_pkey" PRIMARY KEY using index "authors_pkey";

alter table "public"."notes" add constraint "notes_author_id_fkey" FOREIGN KEY (author_id) REFERENCES authors(id) not valid;

alter table "public"."notes" validate constraint "notes_author_id_fkey";

grant delete on table "public"."authors" to "anon";

grant insert on table "public"."authors" to "anon";

grant references on table "public"."authors" to "anon";

grant select on table "public"."authors" to "anon";

grant trigger on table "public"."authors" to "anon";

grant truncate on table "public"."authors" to "anon";

grant update on table "public"."authors" to "anon";

grant delete on table "public"."authors" to "authenticated";

grant insert on table "public"."authors" to "authenticated";

grant references on table "public"."authors" to "authenticated";

grant select on table "public"."authors" to "authenticated";

grant trigger on table "public"."authors" to "authenticated";

grant truncate on table "public"."authors" to "authenticated";

grant update on table "public"."authors" to "authenticated";

grant delete on table "public"."authors" to "service_role";

grant insert on table "public"."authors" to "service_role";

grant references on table "public"."authors" to "service_role";

grant select on table "public"."authors" to "service_role";

grant trigger on table "public"."authors" to "service_role";

grant truncate on table "public"."authors" to "service_role";

grant update on table "public"."authors" to "service_role";